import type { HeroPlayableSpec } from "./playableSpecTypes";

export const defaultPlayableSpec: HeroPlayableSpec = {
  version: "1.0",
  hero: {
    id: "flame_guardian",
    name: "Flame Guardian",
    title: "Guardian of the Ashen Front",
    role: "burst_mage",
    max_hp: 1000,
    move_speed: 5.5,
    attack_damage: 45,
    attack_range: 6,
    resource_type: "mana",
    max_resource: 100,
  },
  gameplay_tags: ["fire", "burst", "area_damage"],
  skills: [
    {
      slot: "Q",
      name: "Blazing Impact",
      type: "projectile",
      cooldown: 4,
      resource_cost: 20,
      damage: 120,
      range: 14,
      radius: 1.2,
      speed: 16,
      description: "Launches a fireball that bursts on hit.",
      vfx: {
        theme: "fire",
        color: "#ff5a1f",
        shape: "fireball",
        impact: "explosion",
        trail: "ember_trail",
      },
    },
    {
      slot: "W",
      name: "Ashen Field",
      type: "aoe_dot",
      cooldown: 10,
      resource_cost: 35,
      damage: 28,
      range: 10,
      radius: 4,
      duration: 5,
      tick_interval: 1,
      description: "Creates a burning zone that damages enemies over time.",
      vfx: {
        theme: "fire",
        color: "#ff8a2a",
        shape: "circle_zone",
        impact: "burning_ground",
        trail: "rising_embers",
      },
    },
    {
      slot: "E",
      name: "Cinder Dash",
      type: "dash",
      cooldown: 8,
      resource_cost: 25,
      damage: 70,
      distance: 7,
      radius: 1.5,
      duration: 0.35,
      description: "Dashes forward and leaves a burning trail.",
      vfx: {
        theme: "fire",
        color: "#f97316",
        shape: "trail",
        impact: "flame_sweep",
        trail: "dash_flame",
      },
    },
    {
      slot: "R",
      name: "Meteor Judgment",
      type: "aoe",
      cooldown: 45,
      resource_cost: 70,
      damage: 320,
      range: 16,
      radius: 5.5,
      duration: 1.2,
      description: "Calls down a meteor that erupts in a wide area.",
      vfx: {
        theme: "fire",
        color: "#ff3d00",
        shape: "meteor",
        impact: "large_explosion",
        trail: "falling_fire_tail",
      },
    },
  ],
  runtime: {
    control_scheme: "wasd_mouse",
    camera: "third_person_follow",
    map_profile: "default_training_arena",
  },
};
